---
- name: install royal-tsx
  shell: brew cask install --appdir="/Applications" royal-tsx

- name: install slack
 shell: brew cask install --appdir="/Applications" slack
 ignore_errors: yes # preinstalled version causing error

- name: install teams
 shell: brew cask install --appdir="/Applications" microsoft-teams

- name: install spotify
  shell: brew cask install --appdir="/Applications" spotify

- name: install visual studio code
 shell: brew cask install --appdir="/Applications" visual-studio-code

- name: install node.js
  homebrew:
    name: node

- name: autohide OSX dock
  shell: defaults write com.apple.dock autohide true
  notify: restart dock

- name: pin OSX dock to right edge
  shell: defaults write com.apple.dock orientation left
  notify: restart dock

- name: display bluetooth in menu bar
  shell: defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
  notify: restart systemui
