---
- name: install ag
  homebrew:
    name: the_silver_searcher
    state: latest

- name: install royal-tsx
  shell: brew cask install royal-tsx

- name: install slack
  shell: brew cask install slack
  ignore_errors: yes # preinstalled version causing error

- name: install libressl for teams
  shell: brew install libressl

- name: install teams
  shell: brew cask install microsoft-teams

- name: install fswatch
  homebrew:
    name: fswatch
    state: latest

- name: autohide OSX dock
  shell: defaults write com.apple.dock autohide true
  notify: restart dock

- name: pin OSX dock to right edge
  shell: defaults write com.apple.dock orientation left
  notify: restart dock

- name: display bluetooth in menu bar
  shell: defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
  notify: restart systemui
